multivews: true

source:         .
destination:    ./_site
includes:       ./_includes

pygments:       true
markdown:       kramdown
permalink:      /:year/:month/:day/:title.html

name: 	        JasonHeppler.org		
base_url:       http://jasonheppler.org
local_url:      /
description:    "A blog covering digital history, technology, and the cultural history of computers"
root_desc:      "JasonHeppler.org"

exclude: ['Rakefile', 'README.markdown', 'config.rb']
